config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es|fr/ do
    root 'application#index'
  end

  resources :users, only: [:new, :show, :edit, :create, :destroy, :update]
  resources :organizations, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    resources :posts do
      resources :chains do
        resources :messages
      end
    end
  end

  get '/home' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/data' => 'visualizations#index'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]

  match '/signin' => 'sessions#create', :as => :signin, via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_languages
  has_many :languages, through: :user_languages
  has_many :posts, foreign_key: :author_id
  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :received_messages, class_name: "Message", foreign_key: :receiver_id

  has_secure_password :validations => false
  validate :facebook_password_check

  mount_uploader :photo, PhotoUploader

  # attr_accessible :photo, :photo_cache, :remove_photo

  def self.create_with_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_create
    user_info = user.facebook_email(auth)
    user.update(
        first_name: auth.info.name.split(" ")[0],
        last_name: auth.info.name.split(" ")[1],
        email: user_info["email"] ||= "no email provided",
        password_digest: "",
      )
  end

  def password
    @password ||= self.password_digest && BCrypt::Password.new(self.password_digest)
  end

  def facebook_email(auth)
    token = auth['credentials']['token']
    @graph = Koala::Facebook::API.new(token)
    @graph.get_object("me?fields=email")
  end


  def facebook_password_check
      if self.uid == nil && self.password == nil
        self.errors[:password] << 'needed!'
      end
  end

  validates_presence_of :first_name, :last_name, :email

  def full_name
    self.first_name + " " + self.last_name
  end

  def display_languages
    language_names = []
    self.languages.each do |language|
      language_names << language.name
    end
    language_names.join(", ")
  end

  def get_volunteer_posts
    @volunteer_posts = []
    self.posts.each do |post|
      if post.volunteer == true
        @volunteer_posts << post
        end
      end
    @volunteer_posts
  end

  def count_volunteer_posts
    self.get_volunteer_posts.count
  end

  def update_known_languages(language_array)
    language_array.each do |new_language|
      possible_new = Language.find_by(name: new_language)

      unless self.languages.include?(possible_new)
        self.languages << possible_new
      end
    end
  end

  def get_new_languages(language_params)
    languages = []
    language_params.each do |array|
        if array.include?("on")
          languages << array[0]
        end
      end
      languages
  end

  def valid_edit_form?(params)
    params[:user][:first_name] != "" && params[:user][:last_name] != "" && params[:user][:email] != ""
  end

  def known_language?(language_name)
    unless self.languages.empty?
      self.languages.each do |language|
        if language_name == language.name
          return true
        end
      end
    end
  end

  def messages
    Message.all.where("(sender_id = ? or receiver_id = ?)", self.id, self.id)
  end

  def chains
    user_chains = []
    self.messages.each do |message|
      unless user_chains.include?(message.chain)
        user_chains << message.chain
      end
    end
    if user_chains == [nil]
      return []
    else
      return user_chains
    end
  end

  def already_messaged?(post)
    self.chains.each do |chain|
      if chain.post_id == post.id
        return true
      end
    end
    false
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    if request.xhr?
      render partial: "layouts/register", locals: { user: @user }
    end
  end

  def create
    @user = User.new(user_params)
    p user_params
    if request.xhr?
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
      else
        render :status => 400
      end
    else
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_url
      else
        render :status => 400
      end
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if request.xhr?

      if params[:photo]
        p params[:photo]
        @user.update_attributes(photo: params[:photo])
      elsif @user.valid_edit_form?(params)
        p params
        @user.update_attributes(user_params)
        puts @user.errors.full_messages
        if params[:language]
          @user.update_known_languages(@user.get_new_languages(params[:language]))
        end
      else
        render :status => 400
      end
    end
  end

  def edit
  end

  def destroy
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :photo)
  end

  def update_user_params
    params[:user].delete(:password) if params[:user][:password].blank?
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # def current_user
  #   @current_user ||= User.find_by(id: session[:user_id])
  # end
end

app/views/users/_user_post_listing.html.erb
<div class="individual-post-listing">
  <h4><%= link_to "#{post.title}", category_post_path(post.category,post) %></h4>
    <p id="post-date"><%= post.posted_date %></p>
    <% if current_user && post.author_id == current_user.id %>
      
      <p class="edit-delete category-show-page"><span class="edit-delete"><i class="fa fa-trash-o fa-1x"></span></i><%= link_to " Delete this post", [post.category, post], id: "delete-post-link" %></p>
    <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="container">
<h1>Register with Your Email Here</h1>
  <div class="errors">
    <% if @user.errors %>
      <% @user.errors.full_messages.each do |error| %>
        <ul><%= error %></ul>
      <% end %>
    <% end %>
  </div>

  <%= form_for(@user) do |f| %>
    <div class="field">
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.text_field :last_name%>
    </div>

    <div class="field">
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :photo, "Upload photo:" %>
      <%= f.file_field :photo%>
    </div>

    <div class="field actions">
      <%= f.submit "Sign Up"%>
    </div>
  <% end %>
  <h1>Or Register with Facebook Here</h1>
  <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
</div>

app/views/users/show.html.erb
<div class= "headings profile-header">
  <div class="row" id="user-container">
  <div class="col-sm-4 user-info">
    <h2>Languages</h2> <h3><%= @user.display_languages  %></h3>
    <% if current_user && current_user == @user %>
    <% end %>
  </div>
  <div class="col-sm-4 center-block">
    <h3 class="notranslate"><%= @user.full_name%></h3>
    <h5 id="update"><%= link_to "Update Info", edit_user_path(current_user)%></h5>
  <div id="user-image" style="image">
    <% if @user.uid %>
      <img class="img-circle" src= <%="http://graph.facebook.com/#{@user.uid}/picture?type=large" %>>
    <% else %>
      <% if @user.photo? %>
        <%= image_tag @user.photo_url, class: "img-circle" %>
      <% else %>
        <%= image_tag "chicago-star" %>
      <% end %>
        <!-- <form class="update-image-form" action="/users/<%#= @user.id %>" method="put">
>>>>>>> master
          <button type="button" class="close pull-right" id="x" aria-hidden="true">×</button>
          <label> Upload Profile Picture </label>
          <input type="file" name="user[photo]">
          <input type="submit" class="btn btn-large" id="photo-submit-button" value="Update">
        </form> -->
    <% end %>
  </div>
  </div>
  <div class="col-sm-4" id="user-details">
    <h2>Member Since: </h2><h3><%=@user.created_at.strftime("%B #{@user.created_at.day.ordinalize}, %Y")%></h3>
    <h2>Volunteer total: </h2><h3><%=@user.count_volunteer_posts%> posts</h3>
  </div>
</div>


</div>




<div id="message-container">

</div>



<div id="edit-form" class="row">
  <div class="col-lg-3"></div>
  <div class= "col-lg-6" id="edit-user-container">
    <form>
      <button type="button" class="close pull-right" id="x" aria-hidden="true">×</button>
    </form>
    <h2>Update Your Info Here!</h2>
   <div class="errors">
    <% if @user.errors %>
      <% @user.errors.full_messages.each do |error| %>
        <ul><%= error %></ul>
      <% end %>
    <% end %>
  </div>
    <div id="edit-user-form-container">
      <form class="user-edit" action="/users/<%= @user.id %>" method="put">
        <div id="new-user-info">
          <label  for="user[first_name]"> First Name: </label>
          <input class="notranslate" id="text" name="user[first_name]" type="text" value=<%=@user.first_name%>><br>
          <label for="user[last_name]"> Last Name: </label>
          <input class="notranslate" id="text" name="user[last_name]" type="text" value=<%=@user.last_name%>><br>
          <label for="user[email]"> Email: </label>
          <input class="notranslate" id="text" name="user[email]" type="text" value=<%=@user.email %>><br>
          <label for="laguange"> Languages(select all that apply) </label>
          <input id="check" type="checkbox" name="language[English]" <% if @user.known_language?("English")%> checked <% end %>> English
          <input id="check" type="checkbox" name="language[Spanish]" <% if @user.known_language?("Spanish")%> checked <% end %>> Spanish
          <input id="check" type="checkbox" name="language[Polish]" <% if @user.known_language?("Polish")%> checked <% end %>> Polish
          <input id="check" type="checkbox" name="language[Russian]" <% if @user.known_language?("Russian")%> checked <% end %>> Russian
          <input id="check" type="checkbox" name="language[Arabic]" <% if @user.known_language?("Arabic")%> checked <% end %>> Arabic
          <input id="check" type="checkbox" name="language[French]" <% if @user.known_language?("French")%> checked <% end %>> French
          <input id="check" type="checkbox" name="language[Romanian]" <% if @user.known_language?("Romanian")%> checked <% end %>> Romanian
          <input id="check" type="checkbox" name="language[Chinese]" <% if @user.known_language?("Chinese")%> checked <% end %>> Chinese<br>


          <button type="submit" class="btn-info" id="user-form-submit">Update Info</button>
        </div>
      </form>
    </div>
  </div>
  <div class="col-lg-3"></div>
</div>


<div id="user-lists-container" class="text-center">
  <div id="user-posts-index">
    <h2>Recent Posts</h2>
    <nav>
        <ul class="nav nav-pills post-user-tabs">
          <li class="active tab"><a href="#active-posts">Active</a></li>
          <li class="tab"><a href="#inactive-posts">Inactive</a></li>
        </ul>
      </nav>
    <div id="active-posts" class="user-posts">
      <% @user.posts.last(10).reverse.each do |post| %>
        <% if post.active == true %>
          <%= render partial: 'user_post_listing', locals: { post: post } %>
        <% end %>
      <% end %>
    </div>

    <div id="inactive-posts" class="user-posts">
      <% @user.posts.last(10).reverse.each do |post| %>
        <% if post.active == false %>
          <%= render partial: 'user_post_listing', locals: { post: post } %>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if current_user && current_user == @user %>
  <div id="user-chains-index">
    <h2>Recent Messages</h2>
    <div id="user-posts-index-container">
      <% @user.chains.last(10).reverse.each do |chain| %>
        <%= render partial: '/chains/single_chain_listing', locals: { chain: chain } %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>




<!--
<div class="row">
  <div class="col-lg-6 current-posts">
    <h2>Current Posts</h2>
  </div>
  <div class="col-lg-6 recent-messages">
    <h2>Recent Messages</h2>
  </div>
</div> -->


<!--  <div class="row">
            <div class="col-sm-3">
            </div>
            <div class="col-sm-6">
                <img id="star" src="/assets/chicago-star.png"/>
                <img id="star" src="/assets/chicago-star.png"/>
                <img id="star" src="/assets/chicago-star.png"/>
                <img id="star" src="/assets/chicago-star.png"/>
            </div>
            <div class="col-sm-3">
            </div>
        </div> -->

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>