config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es|fr/ do
    root 'application#index'
  end

  resources :users, only: [:new, :show, :edit, :create, :destroy, :update]
  resources :organizations, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    resources :posts do
      resources :chains do
        resources :messages
      end
    end
  end

  get '/home' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/data' => 'visualizations#index'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]

  match '/signin' => 'sessions#create', :as => :signin, via: [:get, :post]

end

app/models/chain.rb
class Chain < ActiveRecord::Base
  belongs_to :post
  has_many :messages





def first_message?
  self.messages.empty?
end

end

app/controllers/chains_controller.rb
 class ChainsController < ApplicationController
  def index
  end

  def show
      @category = Category.find(params[:category_id])
      @chain = Chain.find(params[:id])
      @post = Post.find(params[:post_id])
      if request.xhr?
      p params
      p @chain
      render :show, locals: {chain: @chain, post: @post, category: @category }, :layout => false
    else
      p "FAIL" * 100

    end
  end

  def new
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:post_id])
    @chain = Chain.new
    @post.chains << @chain
    if request.xhr?
      render partial: 'messages/new_message_form', locals: { category: @category, post: @post, chain: @chain }
    else
      render 'new'
    end
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/chains_helper.rb
module ChainsHelper
end

app/views/chains/_single_chain_listing.html.erb
<div class="individual-post-listing" id="<%= chain.id %>">
	<h4><%= link_to "Post: #{chain.post.title}", category_post_path(chain.post.category, chain.post) %></h4>
    <p><%= link_to "RE: #{chain.messages.last.subject}", category_post_chain_path(chain.post.category, chain.post, chain), class: "chain-show" %></p>
		<p id="post-date" class="notranslate"><%= chain.messages.last.created_at.to_date%> - <%=chain.messages.last.sender.full_name %></p>
</div>

app/views/chains/create.html.erb
<h1>Chains#create</h1>
<p>Find me in app/views/chains/create.html.erb</p>

app/views/chains/destroy.html.erb
<h1>Chains#destroy</h1>
<p>Find me in app/views/chains/destroy.html.erb</p>

app/views/chains/edit.html.erb
<h1>Chains#edit</h1>
<p>Find me in app/views/chains/edit.html.erb</p>

app/views/chains/index.html.erb
<h1>Chains#index</h1>
<p>Find me in app/views/chains/index.html.erb</p>

app/views/chains/new.html.erb
<h1>Chains#new</h1>
<p>Find me in app/views/chains/new.html.erb</p>
<div>
  <%= render partial: 'messages/new_message_form', locals: { category: @category, post: @post, chain: @chain } %>
</div>

app/views/chains/show.html.erb
<div id="message-pop-up">
<button type="button" class="close pull-right" id="chain-close" aria-hidden="true">×</button>
  <div class="row">
    <div id="user-messages">
      <%@chain.messages.last(2).reverse.each do |message|  %>
        <div id="message">
          <p class="notranslate">To: <%=message.receiver.full_name %></p>
          <p class="notranslate">From: <%=message.sender.full_name %></p>
          <p>Subject: <%=message.subject%></p>
          <p><%= message.body %></p>

        </div>
      <% end %>

      <form class="mg-btm" id="new-reply-form" action="/categories/<%= @category.id %>/posts/<%= @post.id %>/chains/<%= @chain.id %>/messages" method="post">
        <div class="errors"></div>
        <div class="main">
          <input name="message[subject]" type="text" class="form-control" value="<%=@chain.messages.last.subject%>" autofocus>
          <br>
          <textarea name="message[body]" class="form-control" placeholder="write reply here" cols="50" rows="5"></textarea>
          <span class="clearfix"></span>
        </div>
          <button type="submit" class="btn btn-danger" id="new-reply-submit">Reply</button>
      </form>
    </div>

  </div>
</div>

app/views/chains/update.html.erb
<h1>Chains#update</h1>
<p>Find me in app/views/chains/update.html.erb</p>