config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es|fr/ do
    root 'application#index'
  end

  resources :users, only: [:new, :show, :edit, :create, :destroy, :update]
  resources :organizations, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    resources :posts do
      resources :chains do
        resources :messages
      end
    end
  end

  get '/home' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/data' => 'visualizations#index'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]

  match '/signin' => 'sessions#create', :as => :signin, via: [:get, :post]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorized_organizations
  has_many :organizations, through: :categorized_organizations
  has_many :posts

  validates_presence_of :name

  def services_offered
  	self.posts.where(volunteer: true).order(created_at: :desc)
  end

  def services_wanted
  	self.posts.where(volunteer: false).order(created_at: :desc)
  end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

  def show
  	@category = Category.find(params[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_single_post_listing.html.erb
	<div class="individual-post-listing">




		<h4><%= link_to "#{post.title}", category_post_path(post.category,post) %></h4>
			<p id="post-date"><%= post.posted_date %></p>
			<% if current_user && post.author_id == current_user.id %>
				
				<p class="edit-delete category-show-page"><span class="edit-delete"><i class="fa fa-trash-o fa-1x"></span></i><%= link_to " Delete this post", [post.category, post], id: "delete-post-link" %></p>
			<% end %>
	</div>

app/views/categories/index.html.erb
<div class="headings">
<h1>Services Available</h1>
<h3>Select a category below to volunteer or request a service.</h3>
</div>
<div id="categories-index-container">
	<% @categories.sort.each do |category| %>
		<a href="/categories/<%="#{category.id}"%>">
			<div class="categories-links" >
	      <img class="category-icon" src="/assets/<%=category.name.downcase.split(" ")[0]%>.png">
	      <br>
	      <span> <%= I18n.t("#{category.name.upcase}")%></span>
			</div>
		</a>
	<% end %>
</div>

app/views/categories/show.html.erb
	<div id="new-post-container">
		<%= render partial: 'posts/new_post_form', locals: { post: @post } %>
	</div>
	
	<div id="post-search-results">
		<div class="errors"></div>
	</div>

	<div class="headings">
		<h1><%= @category.name %></h1>
		<h3 class="subtitle">Click on any posts to see details or add a new post.</h3>
		<div id="new-post-button" class="btn btn-info" role="button">
			<% if current_user %>
				<%= link_to 'Add a new post', new_category_post_path(@category), class: "btn-large", id: "volunteer-button" %>
			<% else %>
				<%= link_to 'Signin to volunteer!', signin_path, id: "login-to-post-button"%>
			<% end %>
		</div>
	</div>

<div id="category-show-container">

<div class="column-left" id="category-posts-index">
	<div id="posts-index-container">
		<h2>Services</h2>
			<nav>
				<ul class="nav nav-pills post-tabs">
				  <li class="active tab"><a href="#services-offered">Offered</a></li>
				  <li class="tab"><a href="#services-wanted">Wanted</a></li>
				    <%= form_tag(category_posts_path(@category), :method => "get", class: "pull-right", id: "search-form") do %>
				    <div class="field">
				    	<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search all #{@category.name} posts" %>
				    </div>
				    <%= text_field_tag :category_id, params[:category_id], type: "hidden", value: "#{@category.id}" %>
				    <div class="field actions">
					    <%= submit_tag "Go", class: "btn btn-large", :name => nil %>
					  </div>
				    <% end %>
				</ul>
			</nav>
		<div class="services" id="services-offered" >
		<% @category.services_offered.each do |post| %>
			<% if post.active %>
			<%= render partial: 'single_post_listing', locals: { post: post } %>
			<% end %>
		<% end %>
		</div>

		<div class="services" id="services-wanted" >
		<% @category.services_wanted.each do |post| %>
			<% if post.active %>
			<%= render partial: 'single_post_listing', locals: { post: post } %>
			<% end %>
		<% end %>
		</div>
	</div>
</div>

	<div class="column-right" id="categories-orgs-index">
		<h2>Organizations Available</h2>
				<% @category.organizations.each do |org| %>
			<div id="orgs-index-container">
					<h4><%= org.name %></h4>
					<p><%= org.description %></p>
					<p><a href="<%= org.website %>"><%= org.website %></a></p>
					<p><%= org.address_1 %> <%= org.address_2 %></p>
					<p><%= org.city %> <%= org.state %> <%= org.zip %></p>
			</div>
			<% end %>
	</div>



</div>