config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|es|fr/ do
    root 'application#index'
  end

  resources :users, only: [:new, :show, :edit, :create, :destroy, :update]
  resources :organizations, only: [:index, :show]
  resources :categories, only: [:index, :show] do
    resources :posts do
      resources :chains do
        resources :messages
      end
    end
  end

  get '/home' => 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/data' => 'visualizations#index'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]

  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]

  match '/signin' => 'sessions#create', :as => :signin, via: [:get, :post]

end

app/views/layouts/_login.html.erb
<div class="login-container">
  <div class="row">
    <form class="form-signin mg-btm" id="login-form" action="signin">
    <h3 class="heading-desc">
    <button type="button" class="close pull-right" id="x" aria-hidden="true">×</button>Log in to NoFences</h3>
    <div class="social-box">
      <div class="row mg-btm">
        <div class="col-md-12">
          <a href="auth/facebook" class="btn btn-primary btn-block">
          <i class="icon-facebook"></i>  Login with Facebook
          </a>
        </div>
      </div>
      <div class="errors"></div>
    </div>

    <div class="main">
      <input name="session[email]" type="text" class="form-control" placeholder="Email" autofocus>
      <input name="session[password]" type="password" class="form-control" placeholder="Password">

      <span class="clearfix"></span>
    </div>
    <div class="login-footer">
      <div class="row">
        <div class="col-xs-6 col-md-6">
          <div class="left-section">
            <%= link_to "Sign up now", new_user_path %>
          </div>
        </div>
      <div class="col-xs-6 col-md-6 pull-right">
        <button type="submit" class="btn btn-large btn-danger pull-right" id="login-submit">Login</button>
      </div>
    </div>
    </div>
    </form>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-top" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand notranslate" rel="home" href="#" title="New Fences Logo">

    </a>
      <%= link_to "NoFences", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to I18n.t("Services"), categories_path %></li>
      <li><%= link_to "Data", data_path %></li>
      </ul>
      </li>
      </ul>
    <!-- <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="notranslate"><%= link_to "#{current_user.first_name}", user_path(current_user) %>
          <li><%= link_to I18n.t("Logout"), signout_path %></li>
          <% else %>
          <li><%= link_to I18n.t("Login"), signin_path, id:"login-button" %></li>
          <% end %>

      <!--   <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Languages <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li><%= link_to_unless I18n.locale == :en, "English", locale: :en  %></li>
            <li><%= link_to_unless I18n.locale == :es, "Español", locale: :es  %></li>
            <li><%= link_to_unless I18n.locale == :fr, "Français", locale: :fr  %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
        <li id ="google-translate"><div id="google_translate_element"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_register.html.erb
<div class="register-container">
  <div class="row">
    <%= form_for user, :html => { class: "form-signin mg-btm", 'id' => "register-form"} do |f| %>
    <h3 class="heading-desc">
      <button type="button" class="close pull-right" id="x" aria-hidden="true">×</button>Sign Up For NoFences</h3>
      <div class="social-box">
      <div class="row mg-btm">
        <div class="col-md-12">
          <a href="auth/facebook" class="btn btn-primary btn-block">
          <i class="icon-facebook"></i> Register with Facebook
          </a>
        </div>
      </div>
      <div class="errors"></div>
    </div>
      <div class="main">
        <div class="field">
          <%= f.text_field :first_name, {class: "form-control", placeholder: "First Name"} %>
        </div>

        <div class="field">
          <%= f.text_field :last_name, {class: "form-control", placeholder: "Last Name"} %>
        </div>

        <div class="field">
          <%= f.text_field :email, {class: "form-control", placeholder: "Email"} %>
        </div>

        <div class="field">
          <%= f.password_field :password, {class: "form-control", placeholder: "Password"} %>
        </div>

        <div class="field">
          <%= f.label :photo, "Upload Profile Picture:" %>
          <%= f.file_field :photo%>
        </div>

        <span class="clearfix"></span>

        <div class="login-footer">
          <div class="row">
            <div class="col-xs-6 col-md-6 pull-right">
                <%= f.submit "Sign Up", { class: "btn btn-large btn-danger pull-right", id: "register-submit-button"}%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Nofences</title>
  <!-- Bootstrap Core CSS -->
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>

    <!-- Font Awesome CSS -->
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" %>



    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <style>
      #map {
        width: 100%;
        height: 400px;
        background-color: #CCC;      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>

</head>
<body>
  <%= render partial: "layouts/navbar" %>
  <div class="page-under-nav">
  <div class="overlay"></div>
  <%= render partial: "layouts/login" %>
  <div class="reg-form">
  </div>
    <%= yield %>
  </div>
  </div>
</body>
</html>